spring.application.name=SivajiAndSons

# Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/SivajiAndSons
spring.datasource.username=root
spring.datasource.password=Admin@123
# server.port=8081

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.generate-ddl= true
spring.jpa.hibernate.ddl-auto= update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.jackson.time-zone=Asia/Kolkata

# Mail config

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saranraj@sivajison.com
spring.mail.password=vdybmwkruxsxkmpj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# File Config
file.upload-dir= adminStorage
file.upload-dir2= airlinelogos
spring.servlet.multipart.max-file-size=50MB

#whatsapp
twilio.account.sid=YOUR_TWILIO_SID
twilio.auth.token=YOUR_TWILIO_AUTH_TOKEN
twilio.phone.number=whatsapp:+14155238886
